# Source:
# - https://sli.dev/guide/hosting.html#github-pages
# - https://github.com/pnpm/action-setup#use-cache-to-reduce-installation-time
# - https://github.com/crazy-max/ghaction-github-pages#inputs
# - https://sli.dev/guide/hosting.html#base-path
name: Deploy pages

on: push

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-node@v2
        with:
          node-version: "16.14.2"

      - name: Cache pnpm modules
        uses: actions/cache@v2
        with:
          path: ~/.pnpm-store
          key: ${{ runner.os }}-${{ hashFiles('**/pnpm-lock.yaml') }}
          restore-keys: |
            ${{ runner.os }}-

      - uses: pnpm/action-setup@v2.1.0
        with:
          version: 6.25.1
          run_install: true

      - name: Build
        run: pnpm build

      - name: Deploy pages
        uses: crazy-max/ghaction-github-pages@v2
        with:
          build_dir: dist
          jekyll: false
          verbose: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
